Update build-yaap.yml

diff --git a/.github/workflows/build-yaap.yml b/.github/workflows/build-yaap.yml
--- a/.github/workflows/build-yaap.yml
+++ b/.github/workflows/build-yaap.yml
@@ -1,6 +1,4 @@
-
-
-name: Build-Yaap
+name: Build YAAP2 OnePlus_Kernel
 on:
   workflow_dispatch:
     inputs:
@@ -24,39 +22,44 @@ on:
         description: "内核版本"
         required: true
         default: '6.1'
-      KSUNEXT_ENABLED:
-        description: "添加 KSU NEXT"
+      KERNEL_NAME:
+        description: "修改内核名称"
         required: true
-        type: boolean
-        default: true
+        default: '-android14-11-o-g1132d864665d'
+      kernelsu_variant:
+        description: "选择 KSU"
+        required: true
+        type: choice
+        options:
+          - Kernel
+          - KSU_Next
+        default: KSU_Next
+      kernelsu_version:
+        description: "选择 KSU 版本"
+        required: true
+        type: choice
+        options:
+          - without ksu
+          - tag
+          - main
+        default: main
       SUSFS_ENABLED:
         description: "添加 SUSFS"
         required: true
         type: boolean
         default: true
-      KERNEL_TIME:
-       description: "内核构建日期更改(默认为原厂)"
-       required: true
-       default: 'Tue Dec 17 23:36:49 UTC 2025'
-      scx_enable:
-        description: '是否安装风驰内核驱动'
+      VFS_patch_ENABLED:
+        description: "添加vfs补丁（新钩子）？"
         required: true
         type: choice
-        default: 'true'
         options:
-          - 'true'
-          - 'false'
-    
+          - enable
+          - disable
+        default: enable
 jobs:
   build:
     runs-on: ubuntu-latest
-    env:
-      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
-      CCACHE_NOHASHDIR: "true"
-      CCACHE_HARDLINK: "true"
-      CCACHE_DIR: /home/runner/.ccache  
-      CCACHE_MAXSIZE: 8G
-    
+
     steps:
       - name: Maximize build space
         uses: easimon/maximize-build-space@master
@@ -67,145 +70,121 @@ jobs:
           remove-android: 'true'
           remove-haskell: 'true'
           remove-codeql: 'true'
-          
+
       - name: Configure Git
         run: |
-         git config --global user.name "build"
-         git config --global user.email "3436378798@qq.com"
+          git config --global user.name "ychenxuan"
+          git config --global user.email "3494167979@qq.com"
 
       - name: Install dependencies
         run: |
-         sudo apt-get update
-         sudo apt-get install lld
-         sudo apt-get install llvm
-         sudo apt update && sudo apt upgrade -y
-         sudo apt install -y python3 git curl
+          sudo apt update && sudo apt upgrade -y
+          sudo apt install -y python3 git curl lld llvm libelf-dev dwarves
 
       - name: Install repo tool
         run: |
-         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
-         chmod a+x ~/repo
-         sudo mv ~/repo /usr/local/bin/repo
+          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
+          chmod a+x ~/repo
+          sudo mv ~/repo /usr/local/bin/repo
 
       - name: Initialize repo and sync
         run: |
-         mkdir kernel_workspace && cd kernel_workspace
-         repo init -u https://github.com/userxiaoge/opsm8650_kernel_manifest.git -b refs/heads/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
-         repo sync
-         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
-         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
-         sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
-         sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion
+          mkdir kernel_workspace && cd kernel_workspace
+          git clone https://github.com/yaap/kernel_oneplus_sm8650.git -b fifteen kernel_platform
+          rm -rf kernel_platform/android/abi_gki_protected_exports_*
+          sed -i 's/ -dirty//g' kernel_platform/scripts/setlocalversion || true
 
-      - name: Run sed and perl Commands
+      
+
+      - name: Add make name
         run: |
-          echo "Changing to configuration directory: $CONFIG..."
-          cd "kernel_workspace/kernel_platform"
-          
+          cd kernel_workspace/kernel_platform
           echo "Running sed commands..."
-          
+
+          #sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' "./arch/arm64/configs/gki_defconfig"
+          #sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "./arch/arm64/configs/gki_defconfig"
+          #sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "./arch/arm64/configs/gki_defconfig"
+
           # Run sed commands for modifications
-          sed -i 's/check_defconfig//' ./common/build.config.gki
-          sed -i 's/-dirty//' ./common/scripts/setlocalversion
-          sed -i 's/-dirty//' ./msm-kernel/scripts/setlocalversion
-          sed -i '$s|echo "\$res"|echo "\-android14-11-o-g1132d864665d"|' ./common/scripts/setlocalversion
-          sed -i '$s|echo "\$res"|echo "\-android14-11-o-g1132d864665d"|' ./msm-kernel/scripts/setlocalversion
-          sed -i "/stable_scmversion_cmd/s/-maybe//g" ./build/kernel/kleaf/impl/stamp.bzl
-          
-         
-          # Run perl command to modify UTS_VERSION
-          perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./common/scripts/mkcompile_h
+          sed -i 's/check_defconfig//' ./build.config.gki
+          sed -i '$s|echo "\$res"|echo "\-Kim.Jongun"|' ./scripts/setlocalversion
+          sed -i 's/-dirty//' ./scripts/setlocalversion
 
-      - name: Set up SukiSU-Ultra
-        if: github.event.inputs.KSUNEXT_ENABLED == 'true'
-        run: |
-         cd kernel_workspace/kernel_platform
-         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-1.5.8
-         cd KernelSU
-         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
-         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-         sed -i "32s/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
-         
-      - name: Set up susfs
-        if: github.event.inputs.SUSFS_ENABLED == 'true'
-        run: |
-           cd kernel_workspace
-           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
-           git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git
-           cd kernel_platform
-           cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
-           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
-           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
-           
-           # Apply patches
-           cd KernelSU
-           cp ../../SukiSU_patch/hooks/* ./
-           patch -p1 < ksu_hooks.patch || true
-           patch -p1 < new_hooks.patch || true
-           patch -p1 < syscall_hooks.patch || true
-           cd ../common
-           patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
-           cp ../../SukiSU_patch/69_hide_stuff.patch ./
-           patch -p1 -F 3 < 69_hide_stuff.patch
 
-      - name: Add KPROBES 钩子
+      - name: Build kernel
+        if: github.event.inputs.CPU != 'sm8650'
         run: |
           cd kernel_workspace/kernel_platform
-          echo "CONFIG_KPROBES=y" >> ./common/arch/arm64/configs/gki_defconfig
+          make ARCH=arm64 CC=clang LLVM=1 LLVM_IAS=1 -j$(nproc --all) O=out gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config vendor/oplus/waffle.config # Build the kernel config
+          make ARCH=arm64 CC=clang LLVM=1 LLVM_IAS=1 -j$(nproc --all) O=out # Build the kernel itself
+          make ARCH=arm64 CC=clang LLVM=1 LLVM_IAS=1 -j$(nproc --all) O=out modules_install INSTALL_MOD_PATH=./Kernel_Prebuilts # Save the kernel modules to out/Kernel_Prebuilts/lib/modules
+          make ARCH=arm64 CC=clang LLVM=1 LLVM_IAS=1 -j$(nproc --all) O=out install INSTALL_PATH=./Kernel_Prebuilts # Save the kernel image(s) and devicetrees to ./Kernel_Prebuilts/boot hopefully
+          make ARCH=arm64 CC=clang LLVM=1 LLVM_IAS=1 -j$(nproc --all) O=out headers_install INSTALL_HDR_PATH=./Kernel_Prebuilts/usr # Save the kernel headers to out/Kernel_Prebuilts/usr
 
-      - name: Add KPM 支持
-        run: |
-          cd kernel_workspace/kernel_platform
-          echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
+      - name: Set Timestamp
+        id: timestamp
+        run: echo "CURRENT_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
 
-      - name: 应用 lz4k 补丁
+      - name: Prepare and Package AnyKernel3 (Image Only)
         run: |
-            cd kernel_workspace/kernel_platform/common
-            ls
-            cp -r ../../SukiSU_patch/other/zram/lz4k/include/linux/* ./include/linux/
-            cp -r ../../SukiSU_patch/other/zram/lz4k/lib/* ./lib
-            cp -r ../../SukiSU_patch/other/zram/lz4k/crypto/* ./crypto
-            cp ../../SukiSU_patch/other/zram/zram_patch/6.1/lz4kd.patch ./
-            patch -p1 -F 3 < lz4kd.patch || true
+          # --- Clone AnyKernel3 ---
+          echo "Cloning AnyKernel3..."
+          git clone https://github.com/cabagekiller/AnyKernel3.git -b gki-2.0 --depth=1 AnyKernel3
+          rm -rf AnyKernel3/.git
 
-        
-      - name: 添加风驰驱动
-        if: github.event.inputs.scx_enable == 'true'
-        run: |
-          cd kernel_workspace/kernel_platform
-          git clone https://github.com/HanKuCha/sched_ext.git
-          rm -rf ./sched_ext/.git
-          rm -rf ./sched_ext/README.md
-          cp -r ./sched_ext/* ./common/kernel/sched
+          # --- Copy Kernel Image ---
+          echo "Copying kernel Image..."
+          cp kernel_workspace/kernel_platform/out/arch/arm64/boot/Image AnyKernel3/
+          # Optional: cp kernel_workspace/kernel_platform/out/arch/arm64/boot/Image ./kernel_workspace/kernel
 
-          
-      - name: 构建内核
-        run: |
-          export KBUILD_BUILD_TIMESTAMP="${{ github.event.inputs.KERNEL_TIME }}"
-          export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH"
-          export PATH="/usr/lib/ccache:$PATH"
-          sudo apt install libelf-dev
-          cd kernel_workspace/kernel_platform/common
-          make -j$(nproc --all) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld  HOSTLD=ld.lld O=out KCFLAGS+=-O2 gki_defconfig all
-         
-      - name: Apply Linux Patch
-        run: |
-         cd kernel_workspace/kernel_platform/common/out/arch/arm64/boot
-         curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
-         chmod +x patch_linux
-         ./patch_linux
-         rm -f Image
-         mv oImage Image
-         
-      - name: Make AnyKernel3
-        run: |
-         git clone https://github.com/Kernel-SU/AnyKernel3.git --depth=1      
-         rm -rf ./AnyKernel3/.git
-         rm -rf ./AnyKernel3/push.sh
-         cp kernel_workspace/kernel_platform/common/out/arch/arm64/boot/Image ./AnyKernel3/
+          # --- Skip Module Handling ---
+          echo "Skipping kernel module copy and cleanup..."
 
-      - name: Upload AnyKernel3
-        uses: actions/upload-artifact@v4
+          # --- Set up Zip Name ---
+          ZIP_FILENAME="AnyKernel3-ImageOnly_${KSUVER}_${CONFIG_NAME:-default}_pineapple_${CURRENT_TIMESTAMP}.zip" # Adjusted name
+          echo "ZIP_FILENAME=${ZIP_FILENAME}" >> $GITHUB_ENV
+          echo "Final zip name will be: ${ZIP_FILENAME}"
+
+          # --- Create the Zip File ---
+          echo "Creating zip file: ${ZIP_FILENAME}..."
+          cd AnyKernel3
+          # Zip contents, excluding the base 'modules' directory just in case
+          zip -r9 "../${ZIP_FILENAME}" * -x ".git*" -x "LICENSE" -x "README.md" -x "*.zip" -x modules
+          cd ..
+          echo "Zip file created."
+
+          # --- Verify Zip Contents ---
+          echo "Listing contents of ${ZIP_FILENAME}..."
+          unzip -l "${ZIP_FILENAME}" | grep Image || echo "::warning::Could not verify Image in zip listing."
+
+        env:
+          KSUVER: ${{ env.KSUVER }}
+          CURRENT_TIMESTAMP: ${{ env.CURRENT_TIMESTAMP }}
+          # CONFIG_NAME: default # Example if needed
+        working-directory: ${{ github.workspace }}
+
+      - name: Create Release
+        id: create_release
+        uses: softprops/action-gh-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # Pass other variables needed ONLY for the 'name' or 'body' if not set via $GITHUB_ENV earlier
+          # Example: ROOT_DIR_PREFIX: ${{ env.ROOT_DIR_PREFIX }}
         with:
-         name: SuKiSu_${{ env.KSUVER }}_oneplus_12
-         path: ./AnyKernel3/*
+          # Use the correct variable set by the previous step. Assumes file is in workspace root.
+          files: ${{ env.ZIP_FILENAME }}
+          # Ensure CURRENT_TIMESTAMP was set via $GITHUB_ENV in an earlier step
+          tag_name: release-${{ env.CURRENT_TIMESTAMP }}
+          # Use the correct ZIP_FILENAME in the release name too
+          name: Release ${{ env.ROOT_DIR_PREFIX }} ${{ env.ZIP_FILENAME }} # Make sure ROOT_DIR_PREFIX is set earlier too
+          body: |
+            Release for ${{ env.ROOT_DIR_PREFIX }} based on branch ${{ github.event.inputs.CPU }}.
+            KSU Version: ${{ env.KSUVER }} # Ensure KSUVER is set earlier
+            Timestamp: ${{ env.CURRENT_TIMESTAMP }}
+            Config: ${{ github.event.inputs.FEIL }} # Ensure FEIL is a valid input name
+            Device: ${{ github.event.inputs.CPUD }}
+          draft: false
+          prerelease: false
+        # Add a condition to prevent running if essential variables are missing
+        if: always()
+q
